services:
  - type: web
    name: controle-estoque-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: info
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_APP_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: SMTP_SECURE
        sync: false

  - type: static
    name: controle-estoque-web
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
